[package]
name = "weather"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
reqwest = { version = "0.12.20", features = ["blocking", "json"] }
